spring:
  datasource:
    url: jdbc:mysql://localhost:3308/xyzHotelDB?createDatabaseIfNotExist=true
    password: mysqlshehan99$$
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      continue-on-error: true
      mode: always
  mvc:
    view:
      #prefix: /WEB-INF/
      suffix: .jsp

